<script setup lang="ts">
import { t } from '@/lib/i18n';
import { computed } from "vue";
import { FileText, Pencil, Trash2, RefreshCw } from "@lucide/vue";
import ConflictEditor from "@/features/conflicts/ConflictEditor.vue";
import { useFilesStore } from "@/stores/files";
import { useConflictsStore } from "@/stores/conflicts";
import { useOperationStore } from "@/stores/operation";
const files = useFilesStore(); const conflicts = useConflictsStore(); const operation = useOperationStore();
const selected = computed(() => files.selectedEntry);
const notices = { get binary() { return t('uiBinaryFilesShowMetadataOnlyf58de3'); }, get unsupportedEncoding() { return t('uiThisFileIsNotValidUTF8TextAndCannotBePreviewed996120'); }, get tooLarge() { return t('uiFileExceedsThe2MiBPreviewLimit238521'); }, get unsupported() { return t('uiOnlyMetadataCanBeViewedForThisFile4a8497'); }, text: "" };
</script>
<template>
  <section class="file-detail" :aria-label="t('uiFileDetailsb9b756')">
    <header><div><span>{{ t('uiWorkingDirectoryReadOnlyPreview0b72fe') }}</span><strong>{{ selected?.relativePath ?? t('uiRepositoryRoot4c3dc5') }}</strong></div><div v-if="selected && selected.kind !== 'restricted'" class="actions"><button :aria-label="t('uiRenameSelectedItemecb8af')" :title="t('uiRename1cd80f')" :disabled="!files.canMutate" @click="files.requestOperation({ kind: 'rename', relativePath: selected.relativePath, newName: selected.name })"><Pencil :size="14" /><span>{{ t('uiRename1cd80f') }}</span></button><button :aria-label="t('uiDeleteSelectedItem324b30')" :title="t('uiMoveToRecoveryAreab04a66')" :disabled="!files.canMutate" @click="files.requestOperation({ kind: 'delete', relativePath: selected.relativePath })"><Trash2 :size="14" /><span>{{ t('uiDelete3755f5') }}</span></button></div></header>
    <div v-if="files.result?.applied" class="result" role="status"><strong>{{ t('uiFileOperationCompleted9e8f41') }}</strong><p v-if="files.result.selectedPath">{{ t('uiTarget647054') }}{{ files.result.selectedPath }}</p><p v-if="files.result.recoveryPath">{{ t('uiRecoveryLocation8d6833') }}<code>{{ files.result.recoveryPath }}</code><span>{{ t('uiOriginalContentIsKeptHereToRestoreItMoveItBackWhenTheOrigina0f366c') }}</span></p></div>
    <div v-if="files.error && !files.confirmation" class="notice error" role="alert"><p>{{ files.error.message }}</p><details v-if="files.error.diagnostics"><summary>{{ t('uiDiagnostics0b673e') }}</summary><pre>{{ files.error.diagnostics }}</pre></details><button v-if="files.result?.applied" :aria-label="t('uiRetryRefreshOnly56c2bf')" :disabled="files.busy" @click="files.retryRefresh"><RefreshCw :size="14" />{{ t('uiRetryRefreshOnly56c2bf') }}</button></div>
    <p v-if="operation.isBlocked || conflicts.hasDirtyDrafts" class="notice">{{ conflicts.hasDirtyDrafts ? t('uiFileManagementIsUnavailableWhileUnsavedConflictDraftsArePres94175d') : t('uiFinishTheCurrentGitOperationOrResolveConflictsFirstYouCanSti0cf28e') }}</p>
    <div v-if="files.previewLoading" class="empty" role="status">{{ t('uiReadingFiled4405f') }}</div>
    <div v-else-if="files.previewError" class="notice error" role="alert"><p>{{ files.previewError.message }}</p><details v-if="files.previewError.diagnostics"><summary>{{ t('uiDiagnostics0b673e') }}</summary><pre>{{ files.previewError.diagnostics }}</pre></details><button :disabled="files.busy" @click="files.selectEntry(selected)">{{ t('uiReload778497') }}</button></div>
    <template v-else-if="files.preview"><div class="metadata">{{ files.preview.byteLength.toLocaleString() }} bytes · {{ files.preview.kind === 'text' ? (files.preview.bom ? 'UTF-8 BOM' : 'UTF-8') : t('uiMetadatadb9e37') }} · {{ files.preview.lineEnding.toUpperCase() }}</div><div v-if="files.preview.kind === 'text' && files.preview.text !== null" class="editor"><ConflictEditor :key="files.preview.token" :model-value="files.preview.text" readonly :label="t('uiReadOnlyFilePreview908a13')" /></div><div v-else class="empty"><FileText :size="30" /><p>{{ files.preview.reason || notices[files.preview.kind] }}</p></div></template>
    <div v-else class="empty"><FileText :size="30" /><p>{{ selected?.kind === 'restricted' ? selected.reason || t('uiRestrictedItemsCannotBeExpandedPreviewedOrModified142e8a') : selected?.kind === 'directory' ? t('uiExpandDirectoriesToViewFilesOrCreateFilesAndFoldersInTheCurre290ef') : t('uiSelectAFileOnTheLeftToPreviewItsContentdb87f6') }}</p><small v-if="selected?.kind === 'directory'">{{ t('uiEmptyDirectoriesAreShownButGitDoesNotTrackThem2778bb') }}</small></div>
  </section>
</template>
<style scoped>
.file-detail { grid-row: 1 / -1; display: flex; flex-direction: column; min-width: 0; min-height: 0; overflow: auto; }header { display: flex; flex-wrap: wrap; gap: 10px; align-items: center; justify-content: space-between; padding: 12px 16px; border-bottom: 1px solid var(--border); background: var(--surface-panel); }header > div:first-child { min-width: 0; flex: 1 1 130px; display: grid; gap: 5px; }header strong { overflow-wrap: anywhere; font-size: 14px; }header span { color: var(--text-muted); font-size: 11px; }.actions { display: flex; flex-wrap: wrap; gap: 6px; }button { display: inline-flex; align-items: center; gap: 5px; padding: 7px 9px; border: 1px solid var(--border); border-radius: 4px; background: var(--surface-panel); }.actions span { color: var(--text); }.empty { flex: 1; min-height: 140px; display: flex; flex-direction: column; justify-content: center; align-items: center; padding: 22px; color: var(--text-muted); text-align: center; overflow-wrap: anywhere; }.empty p { line-height: 1.7; }.metadata { padding: 8px 14px; font-size: 11px; color: var(--text-muted); border-bottom: 1px solid var(--border); }.editor { flex: 1; min-height: 150px; overflow: hidden; }.notice, .result { padding: 10px 14px; margin: 0; border-bottom: 1px solid var(--border); font-size: 12px; overflow-wrap: anywhere; }.result { background: var(--primary-soft); max-height: 180px; overflow: auto; }.result p { margin: 6px 0 0; }.result code { display: block; user-select: text; }.result span { display: block; color: var(--text-muted); margin-top: 4px; font-size: 11px; }.error { color: var(--danger); }pre { white-space: pre-wrap; overflow-wrap: anywhere; max-height: 120px; overflow: auto; }
</style>
