pub mod activity_service;
pub mod ai_chat;
mod ai_conflict_chunks;
mod ai_conflict_context;
mod ai_conflict_protocol;
mod ai_conflict_service;
pub mod ai_context;
pub mod ai_service;
pub mod changes_service;
mod conflict_content;
mod conflict_paths;
pub mod conflict_service;
#[cfg(test)]
mod conflict_service_tests;
pub mod console_exit;
pub mod console_policy;
pub mod console_service;
pub mod diff_parser;
mod file_fingerprint;
mod file_listing;
mod file_mutation;
pub mod file_service;
pub mod history_service;
pub mod mutation_coordinator;
pub mod operation_state;
pub mod refs_service;
pub mod remote_service;
pub mod repository_service;
pub mod repository_watch;
pub mod review_evidence;
mod review_git;
pub mod review_protocol;
pub mod review_service;
pub mod review_skill;
pub mod review_snapshot;
pub mod settings_service;
pub mod stash_service;
pub mod task_branch_service;
pub mod terminal_command;
pub mod terminal_completion;
pub mod terminal_service;
